// <auto-generated />
using System;
using BizSecureDemo22180092.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BizSecureDemo22180092.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310092134_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BizSecureDemo22180092.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FailedLogins")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@test.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgWtsLcyZmlgYtXvqTSk2nli3gpLLsyd9yAuHjhRuLhTbz/J+G2ITsj3SYcFf1W3w=="
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@test.com",
                            PasswordHash = "AQAAAAIAAYagAAAAENNcvWlMzzHbpz9EKgEFj7bWbXolEk7EhtNEgK98yKQ95c/JICM7zzsBL3fxlH1hzw=="
                        });
                });

            modelBuilder.Entity("BizSecureDemo22180092.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 999.99m,
                            CreatedAtUtc = new DateTime(2026, 3, 10, 9, 21, 34, 174, DateTimeKind.Utc).AddTicks(2877),
                            Title = "Premium Package",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 499.99m,
                            CreatedAtUtc = new DateTime(2026, 3, 10, 9, 21, 34, 174, DateTimeKind.Utc).AddTicks(2886),
                            Title = "Standard Package",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 99.99m,
                            CreatedAtUtc = new DateTime(2026, 3, 10, 9, 21, 34, 174, DateTimeKind.Utc).AddTicks(2888),
                            Title = "Basic Package",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
